services:
  php:
    image: esoledad/php:8.5
    working_dir: /app
    entrypoint: /app/docker/php/docker-entrypoint.sh
    command: symfony server:start --allow-all-ip --port 443
    user: root
    depends_on:
      database:
        condition: service_started
    restart: unless-stopped
    environment:
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      DATABASE_URL: postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-!ChangeMe!}@database:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-18}&charset=${POSTGRES_CHARSET:-utf8}
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
    volumes:
      - ./:/app
      - /app/var
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /app/vendor
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    healthcheck:
      test: [ "CMD-SHELL", "symfony server:status | grep -q 'Listening'" ]
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-18}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-!ChangeMe!}
      - POSTGRES_USER=${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "--dbname", "${POSTGRES_DB:-app}", "--username", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
###< doctrine/doctrine-bundle ###

  mkdocs:
    build:
      dockerfile: docker/mkdocs-material/Dockerfile
      context: ./
    profiles: [ "docs" ]
    depends_on:
      phpmetrics:
        condition: service_completed_successfully
    volumes:
      - ./:/docs
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8000 || exit 1" ]
      start_period: 15s
      interval: 5s
      timeout: 3s
      retries: 15
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"

  phpmetrics:
    image: esoledad/php:8.5
    profiles: [ "docs" ]
    working_dir: /app
    command: vendor/bin/phpmetrics --config=phpmetrics.json --report-html=docs/phpmetrics
    volumes:
      - ./:/app

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
