name: CI

on:
  push:
    branches:
      - main
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run PHPUnit
        run: bin/phpunit --testsuite=Unit

  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Create test database
        run: bin/console -e test doctrine:database:create
      - name: Run migrations
        run: bin/console -e test doctrine:migrations:migrate --no-interaction
      - name: Run PHPUnit
        run: bin/phpunit --testsuite=Functional
      - name: Doctrine Schema Validator
        run: bin/console -e test doctrine:schema:validate

  utils-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run PHPUnit
        run: bin/phpunit --testsuite=Utils

  docker-lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true

# todo Find a better way to run OpenAPI linting, the current approach is very slow and resource intensive. Maybe we can run it in a separate job and only on changed files?
#  openapi-lint:
#    name: OpenAPI Lint
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v6
#      - name: Check OpenAPI
#        run: docker compose exec -T php bin/console api:openapi:export --yaml | docker run --rm -i -v $(pwd)/redocly.yaml:/spec/redocly.yaml redocly/cli lint /dev/stdin

  php-lint:
    name: PHP Lint
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint PHP files
        run: php-cs-fixer fix --dry-run --diff --ansi

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint Markdown files
        run: markdownlint "**/*.md"

  security-check:
    name: Security Check
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Check Security
        run: symfony check:security

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.dist.neon

  rector:
    name: Rector
    runs-on: ubuntu-latest
    container:
      image: docker.io/esoledad/php:8.5
      env:
        APP_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Run Rector
        run: vendor/bin/rector process --dry-run
